# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d91ffb6060b1bcfb3ab603586ba1b8234e3cc5cd9ebda2acc1247f6ace18e91fc934f5b70dd691ed41bb25af6f4e498e2cb5125e9a4525434a859e76a723ac

test:
  secret_key_base: 1abdcecbfa94c3f9172504dcc693278eed92cccf5b424e17c233c489ec3f202ee0f7b2925ed7d598648060034ee775566777ffb18a3b261ec930f7b314e100c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
